### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by MistyDaniels** [Media-Ed-Online/intro-web-dev#17]
Im having the same issue as a few others. I followed the directions and waited an hour but my page still hasnt showed. 
I have made sure to push everything .. but still nothing. 

EDIT: So the link https://mistydaniels.github.io/web-dev-hw/project-1/scripts/index.html works? Im feeling a little brain dead at the moment and cant understand why.

![atom error 404](https://user-images.githubusercontent.com/31575831/30236165-e2ae5bec-94d0-11e7-88ec-19cbb29e8f04.png)

![404 error](https://user-images.githubusercontent.com/31575831/30236131-5003c32c-94d0-11e7-962a-503578c175ba.png)

**Comment by JustineEvansUM** [comment]
Hey @MistyDaniels!

The page looks great! The only weird thing is it lives in your scripts folder, which is why you have that extra `/scripts` path AND the filename `index.html` in your URL. Your screenshot shows that you're _trying_ to get it to work in your `/project-1` directory (where it should), so you just need to move it up a directory on your local drive. It should show up as a change on your GitHub Desktop, and when you push it, update on GitHub. Then your index.html will automatically show up for https://mistydaniels.github.io/web-dev-hw/project-1/

**Comment by MistyDaniels** [comment]
Oooh! I gotcha! Thank you so much!
